version: '3'
services:
  web:
    image: bismillahtraders/ca4
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=mlops
    ports:
      - "3000:3000"  
    depends_on:
      - database

  database:
    image: bismillahtraders/ca4db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlops
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: